# Site
repository: unaihuete93/AboutMe
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Unai Huete Beloki
title: Microsoft Technical Trainer @ Microsoft 
email: hueteunai@gmail.com
# email_title: Email (Email title override)
phone: 0034688692733
# phone_title: Phone (Phone title override)
# website: https://aka.ms/SREBook-AmazonUS
# website_title: The Art of SRE with Azure

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: unaihuete
github_username:  unaihuete93
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: unaihuete
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile-picture.png # Directory of profile image (eg. images/prof.jpg)
about_profile_image2: images/srebook.jpg
about_content: | # this will include new lines to allow paragraphs


  Hi, my name is Unai and I´m an Azure Cloud & DevOps expert. Passionate for technology, I have been working mainly on these different areas during the last years:  Cloud Computing/DevOps/SRE.

  From February 2017 to July 2020 I have been working  as a PFE (Premier Field Engineer) giving Support & Education to Microsoft´s customers all around EMEA mainly around the following technologies: DevOps (GitHub/Azure DevOps), SRE, Azure Cloud and SCRUM/Agile. 

  Since July 2020, I am working as Microsoft Technical Trainer on the technologies mentioned above, leading content for "AZ-400: Designing and Implementing Microsoft DevOps Solutions" . Love to learn new things and demo it to customers.

  In 2022, I published my first book "The Art of Site Reliability Engineering (SRE) with Azure".

  <img src="images/srebook.jpg" width="250"/>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Microsoft
        sub_title: Microsoft Technical Trainer
        border: weak
        caption: June 2020 - Present # Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          As a Microsoft Technical Trainer (MTT) I prepared thousands of customers getting ready for Microsoft official Certification exams. Based on my expertise,
          I mainly focus on DevOps, AI and Cloud Architecture related courses/exams (like AZ400,AZ204,AZ305 and AI102). During last years I participated on couple remote conferences and live stream/recorded sessions, for example:

          <iframe width="560" height="315" src="https://www.youtube.com/embed/3Brg_l0vHBo?start=260" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          
          Since early 2021, I also work as the MTT Courseware Lead for the "AZ-400: Designing and Implementing Microsoft DevOps Solutions" exam:
          - Working closely with Content Team to notify, fix and release issues/updates.
          - Defining the structure and content of the course.
          - Helping define exam objetives, gathering feedback from internal community and external SMEs.
        
      - layout: left
        title: Microsoft
        sub_title: Premier Field Enginer - Customer Engineer
        caption: Feb 2017 - June 2020 # Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          As a Customer Enginner, I worked as an expert for Azure DevOps product and DevOps practises. I helped customers around EMEA adopt DevOps practises leveraging Microsoft tools and services. My responsabilities as a Customer Engineer, where to give support and education on the following technologies/practises:
          - Support customers using Azure DevOps : fixing their issues, updating on-premise ADO server solutions, helping them setup CI/CD pipelines,...
          - Workshops about  DevOps fundamentals using ADO and GitHub
              - Agile/Scrum planning using Azure Boards, CI/CD pipeline basics, Package Management, Testing (Unit, integration, UI, Performance, Load,...) and monitoring (using Azure Monitor + Application Insights)
          - Acting as the technical Scrum Master for some companies.
          - Helping customers adopt DevOps practises using Microsoft tools/services (ADO and GitHub mainly)
          - Teach Azure Development basics, services like: Azure WebApps, ACI, AKS, CosmosDB, APIM, ACA, etc.
          - Delivering sessions in conferences.
    
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Navarra (UNAV)
        sub_title: Master´s in Telecommunication Engineering (MIT)
        caption:  2016 - 2018 #Date Range (eg. 2016 - 2018)
        width: 12
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          <img src="images/unav.jpg" width="200"/>

      - layout: left
        title: University of Navarra (UNAV)
        sub_title: BA Electronic of Communications Engineering
        width: 12
        caption:  2011 - 2015 #Date Range (eg. 2016 - 2018)
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          <img src="images/unav.jpg" width="200"/>

      - layout: left
        title: California Polytechnic State University
        sub_title: Exchange Program - EE Electrical Engineering
        caption:  Sept 2014 - Dec 2014  #Date Range (eg. 2016 - 2018)
        width: 12
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          <img src="images/calpoly.png" width="150"/>



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      On my free time a love travelling,  water sports (surfing, Spearfishing and Swimming) and mountain related activities (MTB and Snowboarding).

      <img src="images/travel.png" width="150"/>
      <img src="images/surf.png" width="150"/>
      <img src="images/scuba.png" width="150"/>
      <img src="images/mtb.png" width="150"/>





# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
